# Bridge configuration updated for drone topics using native Ignition Gazebo plugins
# Maps Ignition Gazebo topics to ROS2 topics with proper namespacing

# Timing 
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Drone control 
- ros_topic_name: "/rs1_drone/cmd_vel"
  gz_topic_name: "/model/rs1_drone/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# Odometry output (published by ignition::gazebo::systems::OdometryPublisher)
- ros_topic_name: "/rs1_drone/odom"   
  gz_topic_name: "/model/rs1_drone/odometry_with_covariance"   
  ros_type_name: "nav_msgs/msg/Odometry"   
  gz_type_name: "gz.msgs.OdometryWithCovariance"   
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/rs1_drone/imu"
  gz_topic_name: "/model/rs1_drone/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

# Front camera: RGB
- ros_topic_name: "/rs1_drone/front/image"
  gz_topic_name: "/model/rs1_drone/front_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# Front camera info
- ros_topic_name: "/rs1_drone/front/camera_info"
  gz_topic_name: "/model/rs1_drone/front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Bottom camera: RGB
- ros_topic_name: "/rs1_drone/bottom/image"
  gz_topic_name: "/model/rs1_drone/bottom_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# Bottom camera info
- ros_topic_name: "/rs1_drone/bottom/camera_info"
  gz_topic_name: "/model/rs1_drone/bottom_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS

# GPS/NavSat sensor
- ros_topic_name: "/rs1_drone/navsat"
  gz_topic_name: "/model/rs1_drone/gps"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "ignition.msgs.NavSat"
  direction: GZ_TO_ROS

# Downward sonar/range sensor
- ros_topic_name: "/rs1_drone/sonar"
  gz_topic_name: "/model/rs1_drone/sonar"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

# 2D Lidar sensor
- ros_topic_name: "/rs1_drone/lidar"
  gz_topic_name: "/model/rs1_drone/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS