# Multi-Drone System Configuration
# This file contains parameters for the multi-drone system

multi_drone_manager:
  ros__parameters:
    # Number of drones (will be overridden by launch parameter)
    num_drones: 3
    
    # Control parameters
    control_frequency: 50.0        # Hz - how often to run control loop
    max_drones: 10                # Maximum number of drones allowed
    
    # Status and monitoring
    enable_status_logging: true    # Enable periodic status messages
    status_update_interval: 5.0    # seconds
    
    # Drone control parameters
    drone_control:
      target_height: 2.0           # meters - default hover height
      hover_height_tolerance: 0.1  # meters - acceptable height error
      altitude_gain: 0.8           # proportional gain for altitude control
      max_vertical_speed: 1.0      # m/s - maximum vertical velocity
      obstacle_threshold: 1.5      # meters - minimum distance to obstacles
      
    # Spawning configuration
    spawn_formation:
      type: "circle"               # circle, line, grid
      radius: 3.0                  # meters - for circle formation
      spacing: 2.0                 # meters - for line/grid formation
      height: 1.0                  # meters - initial spawn height
      
    # Topic configuration
    topics:
      cmd_vel_suffix: "/cmd_vel"
      odom_suffix: "/odom"
      imu_suffix: "/imu"
      lidar_suffix: "/lidar"
      joint_states_suffix: "/joint_states"
