RS1 Robot Package | 14250803: drone_swarm::WaypointPlanner Class Reference
drone_swarm::WaypointPlanner Class Reference
Manages waypoint sequences for drone missions.
#include <waypoint_planner.h>
Public Member Functions
WaypointPlanner ()
Default constructor Initialises empty waypoint list with index at zero.
void setWaypoints (const std::vector< geometry_msgs::msg::PoseStamped > &waypoints)
Set new waypoint sequence for mission.
geometry_msgs::msg::PoseStamped getNextWaypoint ()
Get next waypoint and advance index.
geometry_msgs::msg::PoseStamped getCurrentWaypoint () const
Get current waypoint without advancing index.
bool hasNextWaypoint () const
Check if more waypoints are available.
void reset ()
Reset waypoint index to beginning.
double getDistanceToWaypoint (const geometry_msgs::msg::PoseStamped &current_pose) const
Calculate distance to current waypoint.
std::vector< geometry_msgs::msg::PoseStamped > getAllWaypoints () const
Get all waypoints in the current path.
size_t getCurrentWaypointIndex () const
Get current waypoint index.
void setCurrentWaypointIndex (size_t index)
Set current waypoint index.
std::vector< geometry_msgs::msg::PoseStamped > generateRandomWaypoints (const geometry_msgs::msg::PoseStamped &start_pose, int num_waypoints=5, double min_distance=1.0, double max_distance=3.0, double altitude=15.0)
Generate random waypoints for autonomous patrol.
Detailed Description
Manages waypoint sequences for drone missions.
Provides sequential waypoint navigation with distance calculations and waypoint management. Supports dynamic waypoint updates and mission replanning for autonomous drone operations.
Definition at line 26 of file waypoint_planner.h.
Constructor & Destructor Documentation
WaypointPlanner()
drone_swarm::WaypointPlanner::WaypointPlanner ()
Default constructor Initialises empty waypoint list with index at zero.
Definition at line 9 of file waypoint_planner.cpp.
Member Function Documentation
generateRandomWaypoints()
std::vector< geometry_msgs::msg::PoseStamped > drone_swarm::WaypointPlanner::generateRandomWaypoints (const geometry_msgs::msg::PoseStamped & start_pose, int num_waypoints = 5, double min_distance = 1.0, double max_distance = 3.0, double altitude = 15.0)
Generate random waypoints for autonomous patrol.
Parameters
start_pose Starting position for the new route
num_waypoints Number of waypoints to generate (default: 5)
min_distance Minimum distance between consecutive waypoints in metres (default: 1.0)
max_distance Maximum distance between consecutive waypoints in metres (default: 3.0)
altitude Target altitude for waypoints in metres (default: 15.0)
Returns
Vector of randomly generated waypoints
Generates a valid patrol route with the following constraints:
Waypoints within map bounds (x: -50 to 50, y: -50 to 50)
Consecutive points separated by min_distance to max_distance
No path self-intersections (segments don't cross)
Smooth turns with angle constraints to prevent sharp reversals
Definition at line 72 of file waypoint_planner.cpp.
References M_PI.
getAllWaypoints()
std::vector< geometry_msgs::msg::PoseStamped > drone_swarm::WaypointPlanner::getAllWaypoints () const
Get all waypoints in the current path.
Returns
Vector of all waypoints
Used for state preservation during scenario reactions
Definition at line 54 of file waypoint_planner.cpp.
Referenced by drone_swarm::MissionExecutor::saveMissionState().
getCurrentWaypoint()
geometry_msgs::msg::PoseStamped drone_swarm::WaypointPlanner::getCurrentWaypoint () const
Get current waypoint without advancing index.
Returns
Current waypoint in sequence, or empty pose if none available
Does not modify internal state. Safe to call repeatedly.
Definition at line 26 of file waypoint_planner.cpp.
References hasNextWaypoint().
getCurrentWaypointIndex()
size_t drone_swarm::WaypointPlanner::getCurrentWaypointIndex () const
Get current waypoint index.
Returns
Current index in waypoint sequence
Used for state preservation during scenario reactions
Definition at line 58 of file waypoint_planner.cpp.
Referenced by drone_swarm::MissionExecutor::saveMissionState().
getDistanceToWaypoint()
double drone_swarm::WaypointPlanner::getDistanceToWaypoint (const geometry_msgs::msg::PoseStamped & current_pose) const
Calculate distance to current waypoint.
Parameters
current_pose Current drone position
Returns
Euclidean distance to current waypoint in metres
Returns 0.0 if no waypoints available. Uses 3D distance calculation including altitude differences.
Definition at line 42 of file waypoint_planner.cpp.
References hasNextWaypoint().
getNextWaypoint()
geometry_msgs::msg::PoseStamped drone_swarm::WaypointPlanner::getNextWaypoint ()
Get next waypoint and advance index.
Returns
Next waypoint in sequence, or empty pose if none available
Advances internal index after returning waypoint. Check hasNextWaypoint() before calling to avoid empty returns.
Definition at line 18 of file waypoint_planner.cpp.
References hasNextWaypoint().
hasNextWaypoint()
bool drone_swarm::WaypointPlanner::hasNextWaypoint () const
Check if more waypoints are available.
Returns
True if waypoints remain in sequence, false if at end
Definition at line 34 of file waypoint_planner.cpp.
Referenced by getCurrentWaypoint(), getDistanceToWaypoint(), and getNextWaypoint().
reset()
void drone_swarm::WaypointPlanner::reset ()
Reset waypoint index to beginning.
Allows restarting mission from first waypoint without changing the waypoint list.
Definition at line 38 of file waypoint_planner.cpp.
setCurrentWaypointIndex()
void drone_swarm::WaypointPlanner::setCurrentWaypointIndex (size_t index)
Set current waypoint index.
Parameters
index Index to set as current waypoint
Used for state restoration after scenario reactions Clamped to valid range [0, waypoints.size()]
Definition at line 62 of file waypoint_planner.cpp.
Referenced by drone_swarm::MissionExecutor::restoreMissionState().
setWaypoints()
void drone_swarm::WaypointPlanner::setWaypoints (const std::vector< geometry_msgs::msg::PoseStamped > & waypoints)
Set new waypoint sequence for mission.
Parameters
waypoints Vector of stamped poses defining the path
Replaces current waypoint list and resets index to beginning. Waypoints should be ordered for sequential navigation.
Definition at line 11 of file waypoint_planner.cpp.
Referenced by drone_swarm::MissionExecutor::executeDebrisReaction(), drone_swarm::MissionExecutor::executeHikerRescue(), drone_swarm::MissionExecutor::executeWildfireReaction(), and drone_swarm::MissionExecutor::restoreMissionState().
The documentation for this class was generated from the following files:
include/mission/waypoint_planner.h
src/waypoint_planner.cpp