RS1 Robot Package | 14250803: drone_swarm::MissionExecutor Class Reference
drone_swarm::MissionExecutor Class Reference
Advanced mission execution for complex autonomous operations.
#include <mission_executor.h>
Public Member Functions
MissionExecutor ()
Default constructor Initialises mission executor with default parameters.
void setLogger (rclcpp::Logger logger)
Set ROS 2 logger for debugging output.
void setCmdVelPublisher (rclcpp::Publisher< geometry_msgs::msg::Twist >::SharedPtr pub)
Set command velocity publisher.
bool executeWildfireReaction (const geometry_msgs::msg::Point &fire_location, const geometry_msgs::msg::Point &depot_location, const geometry_msgs::msg::Point &helipad_location, WaypointPlanner *path_planner)
Execute wildfire response mission.
bool executeHikerRescue (const geometry_msgs::msg::Point &hiker_location, const geometry_msgs::msg::Point &depot_location, WaypointPlanner *path_planner)
Execute stranded hiker rescue mission.
bool executeDebrisReaction (const geometry_msgs::msg::Point &debris_location, WaypointPlanner *path_planner)
Execute debris obstruction response mission.
void saveMissionState (WaypointPlanner *path_planner)
Save current mission state for later restoration.
bool restoreMissionState (WaypointPlanner *path_planner)
Restore previously saved mission state.
bool isMissionCancelled () const
Check if mission has been cancelled or aborted.
void cancelMission ()
Cancel current mission operations Sets internal flag to stop mission execution.
void reset ()
Reset mission executor for new mission Clears all internal state and prepares for new operations.
Detailed Description
Advanced mission execution for complex autonomous operations.
Placeholder for future implementation of advanced mission types including formation flying, collaborative tasks, and dynamic mission replanning. Currently provides basic structure for mission state management.
Note
Most functionality is commented out for future development
Definition at line 35 of file mission_executor.h.
Constructor & Destructor Documentation
MissionExecutor()
drone_swarm::MissionExecutor::MissionExecutor ()
Default constructor Initialises mission executor with default parameters.
Definition at line 7 of file mission_executor.cpp.
Member Function Documentation
cancelMission()
void drone_swarm::MissionExecutor::cancelMission ()
Cancel current mission operations Sets internal flag to stop mission execution.
Definition at line 35 of file mission_executor.cpp.
executeDebrisReaction()
bool drone_swarm::MissionExecutor::executeDebrisReaction (const geometry_msgs::msg::Point & debris_location, WaypointPlanner * path_planner)
Execute debris obstruction response mission.
Parameters
debris_location Location of debris
path_planner Path planner for waypoint management
Returns
True if mission completed successfully
Generates circular orbit waypoints around debris for visual inspection Allows drone to survey the obstruction from multiple angles
Definition at line 216 of file mission_executor.cpp.
References drone_swarm::WaypointPlanner::setWaypoints().
executeHikerRescue()
bool drone_swarm::MissionExecutor::executeHikerRescue (const geometry_msgs::msg::Point & hiker_location, const geometry_msgs::msg::Point & depot_location, WaypointPlanner * path_planner)
Execute stranded hiker rescue mission.
Parameters
hiker_location Location of stranded hiker
depot_location Location of medkit depot
path_planner Path planner for waypoint management
Returns
True if mission completed successfully
Sequence: Navigate to depot -> Land -> Collect medkit -> Takeoff -> Navigate to hiker -> Deploy medkit -> Return to previous mission
Definition at line 163 of file mission_executor.cpp.
References drone_swarm::WaypointPlanner::setWaypoints().
executeWildfireReaction()
bool drone_swarm::MissionExecutor::executeWildfireReaction (const geometry_msgs::msg::Point & fire_location, const geometry_msgs::msg::Point & depot_location, const geometry_msgs::msg::Point & helipad_location, WaypointPlanner * path_planner)
Execute wildfire response mission.
Parameters
fire_location Location of the fire
depot_location Location of retardant depot
path_planner Path planner for waypoint management
Returns
True if mission completed successfully
Sequence: Navigate to depot -> Land -> Collect retardant -> Takeoff -> Navigate to fire -> Deploy retardant -> Return to previous mission
Definition at line 86 of file mission_executor.cpp.
References drone_swarm::WaypointPlanner::setWaypoints().
isMissionCancelled()
bool drone_swarm::MissionExecutor::isMissionCancelled () const
Check if mission has been cancelled or aborted.
Returns
True if mission should be terminated
Definition at line 31 of file mission_executor.cpp.
reset()
void drone_swarm::MissionExecutor::reset ()
Reset mission executor for new mission Clears all internal state and prepares for new operations.
Definition at line 40 of file mission_executor.cpp.
restoreMissionState()
bool drone_swarm::MissionExecutor::restoreMissionState (WaypointPlanner * path_planner)
Restore previously saved mission state.
Parameters
path_planner Path planner to restore waypoints to
Returns
True if state was restored successfully
Restores waypoint progress after scenario reaction completes
Definition at line 66 of file mission_executor.cpp.
References drone_swarm::WaypointPlanner::setCurrentWaypointIndex(), and drone_swarm::WaypointPlanner::setWaypoints().
saveMissionState()
void drone_swarm::MissionExecutor::saveMissionState (WaypointPlanner * path_planner)
Save current mission state for later restoration.
Parameters
path_planner Path planner with current waypoints
Stores waypoint progress and mission state before scenario reaction
Definition at line 51 of file mission_executor.cpp.
References drone_swarm::WaypointPlanner::getAllWaypoints(), and drone_swarm::WaypointPlanner::getCurrentWaypointIndex().
setCmdVelPublisher()
void drone_swarm::MissionExecutor::setCmdVelPublisher (rclcpp::Publisher< geometry_msgs::msg::Twist >::SharedPtr pub)
Set command velocity publisher.
Parameters
pub ROS 2 publisher for geometry_msgs::msg::Twist
Definition at line 24 of file mission_executor.cpp.
setLogger()
void drone_swarm::MissionExecutor::setLogger (rclcpp::Logger logger)
Set ROS 2 logger for debugging output.
Parameters
logger ROS 2 logger instance
Definition at line 17 of file mission_executor.cpp.
The documentation for this class was generated from the following files:
include/mission/mission_executor.h
src/mission_executor.cpp