RS1 Robot Package | 14250803: drone_swarm::DroneControl Class Reference
drone_swarm::DroneControl Class Reference
Advanced drone control system with multiple control modes.
#include <drone_control.h>
Public Member Functions
DroneControl ()
Default constructor Initialises PID controllers and sets default parameters.
void initialise (double mass, double max_thrust)
Initialise physical parameters.
void setLogger (rclcpp::Logger logger)
Set ROS 2 logger for debugging output.
void setCmdVelPublisher (rclcpp::Publisher< geometry_msgs::msg::Twist >::SharedPtr pub)
Set command velocity publisher.
geometry_msgs::msg::Twist calculateControlOutput (const geometry_msgs::msg::PoseStamped &current_pose, const geometry_msgs::msg::PoseStamped &target_pose, const geometry_msgs::msg::Twist &current_velocity, double dt)
Calculate control output for position tracking.
void updatePositionPIDGains (double kp, double ki, double kd)
Update position PID controller gains.
void setControlLimits (double max_velocity, double max_angular_velocity)
Set control output limits.
void resetControllers ()
Reset all PID controllers Clears integral accumulators and error history.
geometry_msgs::msg::Twist calculateAdvancedPositionControl (const geometry_msgs::msg::PoseStamped &current_pose, const geometry_msgs::msg::PoseStamped &target_pose, double dt, bool use_manual_altitude=true)
Enhanced position control with advanced features.
bool flyToGoal (VehicleData &vehicle, const geometry_msgs::msg::Pose &goal)
High-level navigation to goal pose.
geometry_msgs::msg::Twist navigateToWaypointWithAltitudeControl (const geometry_msgs::msg::PoseStamped &current_pose, const geometry_msgs::msg::PoseStamped &target_waypoint, double sonar_range, const sensor_msgs::msg::LaserScan &lidar_data, double dt=0.1, bool allow_descent=false)
Navigate to 2D waypoint using terrain-following altitude control.
void setTerrainFollowingAltitude (double altitude)
Set target altitude above ground for terrain following.
void setEmergencyClimbParams (double detection_distance, double climb_altitude)
Set emergency climb parameters for obstacle avoidance.
bool takeoff (double target_altitude, double sonar_range, double elapsed_seconds, double max_timeout_seconds=10.0)
Execute takeoff maneuver using sonar feedback.
bool land (double target_altitude, double sonar_range, double elapsed_seconds, double max_timeout_seconds=20.0)
Execute landing maneuver using sonar feedback.
geometry_msgs::msg::Twist calculatePositionControl (const geometry_msgs::msg::PoseStamped &current_pose, const geometry_msgs::msg::PoseStamped &target_pose, double dt)
Basic position control mode.
geometry_msgs::msg::Twist calculateVelocityControl (const geometry_msgs::msg::Twist &current_velocity, const geometry_msgs::msg::Twist &target_velocity, double dt)
Velocity control mode.
double calculateXControl (double target_x, double current_x, double dt)
X-axis position control.
double calculateYControl (double target_y, double current_y, double dt)
Y-axis position control
double calculateZControl (double target_z, double current_z, double dt)
Z-axis position control.
void updateCurrentYaw (double yaw)
Update current yaw angle from IMU data.
double calculateYawToTarget (const geometry_msgs::msg::Point &current_pos, const geometry_msgs::msg::Point &target_pos)
Calculate desired yaw angle towards target.
double calculateYawControl (double target_yaw, double current_yaw, double dt)
Calculate yaw control command.
Detailed Description
Advanced drone control system with multiple control modes.
Provides comprehensive flight control including position control, velocity control, and high-level navigation capabilities with enhanced flyToGoal functionality for autonomous missions.
Definition at line 54 of file drone_control.h.
Constructor & Destructor Documentation
DroneControl()
drone_swarm::DroneControl::DroneControl ()
Default constructor Initialises PID controllers and sets default parameters.
Definition at line 12 of file drone_control.cpp.
Member Function Documentation
calculateAdvancedPositionControl()
geometry_msgs::msg::Twist drone_swarm::DroneControl::calculateAdvancedPositionControl (const geometry_msgs::msg::PoseStamped & current_pose, const geometry_msgs::msg::PoseStamped & target_pose, double dt, bool use_manual_altitude = true)
Enhanced position control with advanced features.
Parameters
current_pose Current drone pose
target_pose Desired target pose
dt Time step since last calculation
use_manual_altitude Enable manual altitude control mode
Returns
Twist command optimised for smooth flight
Definition at line 78 of file drone_control.cpp.
References calculateYawControl(), and calculateYawToTarget().
Referenced by calculateControlOutput(), calculatePositionControl(), flyToGoal(), and navigateToWaypointWithAltitudeControl().
calculateControlOutput()
geometry_msgs::msg::Twist drone_swarm::DroneControl::calculateControlOutput (const geometry_msgs::msg::PoseStamped & current_pose, const geometry_msgs::msg::PoseStamped & target_pose, const geometry_msgs::msg::Twist & current_velocity, double dt)
Calculate control output for position tracking.
Parameters
current_pose Current drone pose
target_pose Desired target pose
current_velocity Current velocity for feedforward control
dt Time step since last calculation
Returns
Twist command for drone actuation
Definition at line 334 of file drone_control.cpp.
References calculateAdvancedPositionControl().
calculatePositionControl()
geometry_msgs::msg::Twist drone_swarm::DroneControl::calculatePositionControl (const geometry_msgs::msg::PoseStamped & current_pose, const geometry_msgs::msg::PoseStamped & target_pose, double dt)
Basic position control mode.
Parameters
current_pose Current drone pose
target_pose Desired target pose
dt Time step since last calculation
Returns
Twist command for position tracking
Definition at line 344 of file drone_control.cpp.
References calculateAdvancedPositionControl().
calculateVelocityControl()
geometry_msgs::msg::Twist drone_swarm::DroneControl::calculateVelocityControl (const geometry_msgs::msg::Twist & current_velocity, const geometry_msgs::msg::Twist & target_velocity, double dt)
Velocity control mode.
Parameters
current_velocity Current measured velocity
target_velocity Desired target velocity
dt Time step since last calculation
Returns
Twist command for velocity tracking
calculateXControl()
double drone_swarm::DroneControl::calculateXControl (double target_x, double current_x, double dt)
X-axis position control.
Parameters
target_x Desired X position
current_x Current X position
dt Time step
Returns
X velocity command
Definition at line 351 of file drone_control.cpp.
calculateYawControl()
double drone_swarm::DroneControl::calculateYawControl (double target_yaw, double current_yaw, double dt)
Calculate yaw control command.
Parameters
target_yaw Desired yaw angle
current_yaw Current yaw angle
dt Time step
Returns
Angular velocity command
Definition at line 374 of file drone_control.cpp.
Referenced by calculateAdvancedPositionControl().
calculateYawToTarget()
double drone_swarm::DroneControl::calculateYawToTarget (const geometry_msgs::msg::Point & current_pos, const geometry_msgs::msg::Point & target_pos)
Calculate desired yaw angle towards target.
Parameters
current_pos Current position
target_pos Target position
Returns
Desired yaw angle in radians
Definition at line 368 of file drone_control.cpp.
Referenced by calculateAdvancedPositionControl().
calculateYControl()
double drone_swarm::DroneControl::calculateYControl (double target_y, double current_y, double dt)
Y-axis position control
Parameters
target_y Desired Y position
current_y Current Y position
dt Time step
Returns
Y velocity command
Definition at line 355 of file drone_control.cpp.
calculateZControl()
double drone_swarm::DroneControl::calculateZControl (double target_z, double current_z, double dt)
Z-axis position control.
Parameters
target_z Desired Z position
current_z Current Z position
dt Time step
Returns
Z velocity command
Definition at line 359 of file drone_control.cpp.
flyToGoal()
bool drone_swarm::DroneControl::flyToGoal (VehicleData & vehicle, const geometry_msgs::msg::Pose & goal)
High-level navigation to goal pose.
Parameters
vehicle Vehicle data structure with current state
goal Target pose to reach
Returns
True if goal reached, false if still navigating
Implements advanced flyToGoal algorithm with obstacle avoidance and smooth trajectory following for autonomous missions.
Definition at line 181 of file drone_control.cpp.
References calculateAdvancedPositionControl(), drone_swarm::VehicleData::current_odom, drone_swarm::VehicleData::id, drone_swarm::VehicleData::mission_active, drone_swarm::VehicleData::odom_mutex, and resetControllers().
initialise()
void drone_swarm::DroneControl::initialise (double mass, double max_thrust)
Initialise physical parameters.
Parameters
mass Drone mass in kilograms
max_thrust Maximum thrust capability in Newtons
Definition at line 38 of file drone_control.cpp.
land()
bool drone_swarm::DroneControl::land (double target_altitude, double sonar_range, double elapsed_seconds, double max_timeout_seconds = 20.0)
Execute landing maneuver using sonar feedback.
Parameters
target_altitude Target landing altitude in metres (typically 0.2m)
sonar_range Current sonar reading in metres
elapsed_seconds Time elapsed since landing started
max_timeout_seconds Maximum time allowed for landing
Returns
True if landing complete (success or timeout), false if still in progress
Handles complete landing logic including velocity command publishing, progress monitoring, and completion detection using sonar feedback. Publishes descent commands until target altitude is reached.
Definition at line 451 of file drone_control.cpp.
navigateToWaypointWithAltitudeControl()
geometry_msgs::msg::Twist drone_swarm::DroneControl::navigateToWaypointWithAltitudeControl (const geometry_msgs::msg::PoseStamped & current_pose, const geometry_msgs::msg::PoseStamped & target_waypoint, double sonar_range, const sensor_msgs::msg::LaserScan & lidar_data, double dt = 0.1, bool allow_descent = false)
Navigate to 2D waypoint using terrain-following altitude control.
Parameters
current_pose Current drone position from odometry
target_waypoint Target waypoint (only X,Y used, Z ignored)
sonar_range Current sonar altitude reading
lidar_data Current LiDAR scan for obstacle detection
dt Time step for control calculations
Returns
Twist command for waypoint navigation with terrain following
Navigates to X,Y coordinates while maintaining constant altitude above ground using sonar feedback. Uses LiDAR to detect obstacles and climb over them.
Definition at line 499 of file drone_control.cpp.
References calculateAdvancedPositionControl().
resetControllers()
void drone_swarm::DroneControl::resetControllers ()
Reset all PID controllers Clears integral accumulators and error history.
Definition at line 67 of file drone_control.cpp.
Referenced by flyToGoal().
setCmdVelPublisher()
void drone_swarm::DroneControl::setCmdVelPublisher (rclcpp::Publisher< geometry_msgs::msg::Twist >::SharedPtr pub)
Set command velocity publisher.
Parameters
pub ROS 2 publisher for geometry_msgs::msg::Twist
Definition at line 49 of file drone_control.cpp.
setControlLimits()
void drone_swarm::DroneControl::setControlLimits (double max_velocity, double max_angular_velocity)
Set control output limits.
Parameters
max_velocity Maximum linear velocity (m/s)
max_angular_velocity Maximum angular velocity (rad/s)
Definition at line 61 of file drone_control.cpp.
setEmergencyClimbParams()
void drone_swarm::DroneControl::setEmergencyClimbParams (double detection_distance, double climb_altitude)
Set emergency climb parameters for obstacle avoidance.
Parameters
detection_distance Distance ahead to scan for obstacles (default 5m)
climb_altitude Additional altitude to climb over obstacles (default 5m)
Definition at line 659 of file drone_control.cpp.
setLogger()
void drone_swarm::DroneControl::setLogger (rclcpp::Logger logger)
Set ROS 2 logger for debugging output.
Parameters
logger ROS 2 logger instance
Definition at line 44 of file drone_control.cpp.
setTerrainFollowingAltitude()
void drone_swarm::DroneControl::setTerrainFollowingAltitude (double altitude)
Set target altitude above ground for terrain following.
Parameters
altitude Target altitude in metres above ground (default 13m)
takeoff()
bool drone_swarm::DroneControl::takeoff (double target_altitude, double sonar_range, double elapsed_seconds, double max_timeout_seconds = 10.0)
Execute takeoff maneuver using sonar feedback.
Parameters
target_altitude Target altitude in metres
sonar_range Current sonar reading in metres
elapsed_seconds Time elapsed since takeoff started
max_timeout_seconds Maximum time allowed for takeoff
Returns
True if takeoff complete (success or timeout), false if still in progress
Handles complete takeoff logic including velocity command publishing, progress monitoring, and completion detection using sonar feedback. Publishes climb commands until target altitude is reached.
Definition at line 386 of file drone_control.cpp.
updateCurrentYaw()
void drone_swarm::DroneControl::updateCurrentYaw (double yaw)
Update current yaw angle from IMU data.
Parameters
yaw Current yaw angle in radians
Definition at line 363 of file drone_control.cpp.
updatePositionPIDGains()
void drone_swarm::DroneControl::updatePositionPIDGains (double kp, double ki, double kd)
Update position PID controller gains.
Parameters
kp Proportional gain
ki Integral gain
kd Derivative gain
Definition at line 54 of file drone_control.cpp.
The documentation for this class was generated from the following files:
include/drone_control.h
src/drone_control.cpp